# Generated by Django 5.2.8 on 2025-11-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
