# Generated by Django 5.2.8 on 2025-11-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_userprofile_email_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
