# Generated by Django 5.2.8 on 2025-11-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0005_rename_firstname_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
