# Generated by Django 5.2.8 on 2025-11-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0006_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
