# Generated by Django 5.2.8 on 2025-11-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
