# Generated by Django 5.2.8 on 2025-11-26 19:27

import logging
from django.db import migrations
from django.contrib.auth import get_user_model
logger = logging.getLogger(__name__)


def create_guest_user(apps, schema_editor):
    USERNAME = "guest@join.com"
    PASSWORD = "SuperSafeGuest123!"
    EMAIL = "guest@join.com"
    FIRST_NAME = "Guest"
    LAST_NAME = "User"
    user = get_user_model()

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        logger.info("Creating new guest user")
        user = user.objects.create_user(
            username=USERNAME,
            password=PASSWORD,
            email=EMAIL,
            first_name=FIRST_NAME,
            last_name=LAST_NAME
        )
        user.save()
    else:
        logger.info("Guest user already created!")


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0009_delete_customuser'),
    ]

    operations = [
        migrations.RunPython(create_guest_user),
    ]
