# Generated by Django 5.2.8 on 2025-11-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_alter_contact_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.CharField(max_length=40),
        ),
    ]
