# Generated by Django 5.2.8 on 2025-11-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('priority', models.TextField(max_length=1)),
                ('category', models.IntegerField(default=0)),
                ('dueDate', models.DateField()),
                ('assignedTo', models.JSONField(blank=True, default=list)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
